### ISSUE TITLE
could you released the code of success plots on otb-2015 on the paper

### ISSUE THREAD

**Issue by iou1992** [egundogdu/CFCF#3]
![3](https://user-images.githubusercontent.com/33022344/38223785-48541662-371f-11e8-8043-bd1fab04fbd7.GIF)
thx advance

**Comment by egundogdu** [comment]
Hi,
The healthiest way to obtain and compare the results w.r.t. to the baseline method C-COT is to run the C-COT source code, which is also available on github by the corresponding authors, in their ECCV setting by replacing the Conjugate Gradient Descent Iteration 5 with 1 (simply set it to 1). In order to obtain the curves, you should change the network from VGG to our available one in this repository. Regarding the code that I originally used, it is a bit untidy, hence, for convenient testing, please download the OTB-2015 toolkit and please use the .m file in C-COT.

**Comment by iou1992** [comment]
ok,
thanks for your reply.
