### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by jimmy-dq** [egundogdu/CFCF#4]
Hi @egundogdu , thanks for your wonderful work. I am confused about how to use your CFCF tracker for testing. Should I replace the VGG model used in the C-COT tracker with your CFCFNet.mat and then run the demo.m in the C-COT code?

**Comment by egundogdu** [comment]
Hi, I think you understood correctly. You will replace VGG model used in C-COT with CFCF.mat. Moreover, you should replace Conjugate Gradient Descent Iteration number with 1. (set this parameter to 1 instead of 5 of the C-COT work.) And then, you should be able to run the demo of C-COT in the same way.

**Comment by jimmy-dq** [comment]
Thank you for your timely reply. I have tried what you said and now the code works well. Thanks a lot !
